version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - ./data/www:/app
    command: yarn serve
    tty: true
    environment:
       VUE_APP_API_ENDPOINT: http://localhost:3000
    ports:
      - 80:8080